import {
  PiWifiHigh,
  PiTowel,
  PiUmbrella,
  PiUmbrellaSimple,
  PiLockers,
  PiLockKey,
  PiShower,
  PiDrop,
  PiHandWaving,
  PiForkKnife,
  PiFirstAidKit,
  PiCar,
  PiWheelchair,
  PiPlugCharging,
  PiPhone,
  PiFan,
  PiBeerBottle,
  PiMartini,
  PiBasket,
  PiLifebuoy,
  PiShieldCheck,
  PiToilet,
  PiSparkle,
  PiSunHorizon,
  PiCouch,
  PiCallBell,
  PiWine,
  PiCoffee,
  PiHouseLine,
  PiUser,
  PiCheckCircle,
  type IconType,
} from 'react-icons/pi';

const EXACT: Record<string, IconType> = {
  'wi-fi': PiWifiHigh,
  wifi: PiWifiHigh,
  towels: PiTowel,
  towel: PiTowel,
  'beach umbrella': PiUmbrella,
  umbrella: PiUmbrellaSimple,
  'sunbed cushion': PiCouch,
  cushion: PiCouch,
  mattress: PiCouch,
  locker: PiLockers,
  lockers: PiLockers,
  'changing room': PiHouseLine,
  'outdoor shower': PiShower,
  shower: PiShower,
  'fresh water': PiDrop,
  water: PiDrop,
  'waiter service': PiCallBell,
  waiter: PiCallBell,
  'table service': PiForkKnife,
  'beach attendant': PiUser,
  'equipment rental': PiBasket,
  'massage on beach': PiSparkle,
  'phone charging': PiPhone,
  charging: PiPlugCharging,
  'cooling mist / fan': PiFan,
  'cooling mist': PiFan,
  fan: PiFan,
  'extra shade': PiUmbrella,
  shade: PiUmbrella,
  'private cabana': PiHouseLine,
  cabana: PiHouseLine,
  'power outlet': PiPlugCharging,
  'beach bar': PiBeerBottle,
  bar: PiWine,
  'soft drinks': PiCoffee,
  'snacks menu': PiBasket,
  'cocktail service': PiMartini,
  cocktails: PiMartini,
  'restaurant access': PiForkKnife,
  restaurant: PiForkKnife,
  lifeguard: PiLifebuoy,
  'first aid': PiFirstAidKit,
  parking: PiCar,
  'wheelchair accessible': PiWheelchair,
  'cctv surveillance': PiShieldCheck,
  cctv: PiShieldCheck,
  'restroom access': PiToilet,
  restroom: PiToilet,
};

const KEYWORD: Array<[RegExp, IconType]> = [
  [/wifi|wi-?fi/i, PiWifiHigh],
  [/towel/i, PiTowel],
  [/umbrella|parasol|shade/i, PiUmbrella],
  [/cushion|mattress|sunbed/i, PiCouch],
  [/locker|lock/i, PiLockKey],
  [/shower/i, PiShower],
  [/water|drop/i, PiDrop],
  [/waiter|attendant|bell/i, PiCallBell],
  [/charg/i, PiPlugCharging],
  [/fan|mist/i, PiFan],
  [/cabana|changing/i, PiHouseLine],
  [/bar|cocktail|martini|wine|beer/i, PiMartini],
  [/snack|food|restaurant|fork/i, PiForkKnife],
  [/coffee|drink|soft/i, PiCoffee],
  [/life.?guard|buoy/i, PiLifebuoy],
  [/first.?aid|medical/i, PiFirstAidKit],
  [/park/i, PiCar],
  [/wheel.?chair|accessib/i, PiWheelchair],
  [/cctv|surveil|security|shield/i, PiShieldCheck],
  [/toilet|restroom|washroom/i, PiToilet],
  [/sun|beach/i, PiSunHorizon],
];

export function getFacilityIcon(name: string): IconType {
  const key = name.trim().toLowerCase();
  if (EXACT[key]) return EXACT[key];
  for (const [re, icon] of KEYWORD) {
    if (re.test(name)) return icon;
  }
  return PiCheckCircle;
}
