'use client'

import { useState } from 'react'
import { useSelector } from 'react-redux'
import { PiGift, PiCopy, PiCheck } from 'react-icons/pi'
import Layout from '@/components/layout/Layout'
import ProfileLayout from '../ProfileLayout'
import { useTranslation } from '@/hooks/useTranslation'
import { userDataSelector } from '@/redux/reducers/userSlice'
import { userDetailsType } from '@/types/GlobalTypes'
import { settingsSelector } from '@/redux/reducers/settingsSlice'

const ReferralEarn = () => {

    const { t } = useTranslation();
    const settingsData = useSelector(settingsSelector);
    const userDetails = useSelector(userDataSelector) as userDetailsType
    const referralCode = userDetails?.referral_code ?? ''
    const [copied, setCopied] = useState(false)

    const HOW_IT_WORKS = [
        {
            step: '01',
            title: t('shareInviteCode'),
            desc: t('shareInviteCodeDesc'),
        },
        {
            step: '02',
            title: t('friendSignsUpBooks'),
            desc: t('friendSignsUpBooksDesc'),
            subLabel: t('couponRules') + ':',
            bullets: [
                t('validOnlyFirstBooking'),
                t('oneCouponPerBooking'),
                t('expiryBasedOnPolicy'),
            ],
        },
        {
            step: '03',
            title: t('friendCompletesFirstStay'),
            desc: t('friendCompletesFirstStayDesc'),
            bullets: [
                t('referralCouponUsed'),
                t('bookingCompletedAfterCheckout'),
            ],
        },
        {
            step: '04',
            title: t('youEarnVoucher'),
            desc: t('youEarnVoucherDesc'),
            bullets: [
                t('rewardCouponAutoGenerated'),
                t('rewardValueManagedByPlatform'),
            ],
        },
    ]

    const handleCopy = () => {
        if (!referralCode) return
        navigator.clipboard.writeText(referralCode).then(() => {
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        })
    }

    return (
        <Layout>
            <ProfileLayout title={t('refrEarn')}>
                <div className="p-5 md:p-6 space-y-6">

                    {/* Banner card */}
                    <div className="successLightBg border successLightBorderColor rounded-xl p-5 space-y-4">
                        <div>
                            <p className="font-semibold">{t('earnDiscountVouchers')}</p>
                            <p className="textSecondaryColor font-medium mt-0.5">{t('referFriendDesc')}</p>
                        </div>
                        <div className="inline-block border successLightBorderColor bg-white rounded-2xl px-4 py-2 font-medium">
                            {t('getUpto')} {settingsData?.referral_settings?.referrer_percentage}% {t('offOnFirstBooking')}
                        </div>
                    </div>

                    {/* How it works */}
                    <div className="space-y-4">
                        <p className="font-semibold">{t('howItWorks')}:</p>
                        <div className="">
                            {HOW_IT_WORKS.map(({ step, title, desc, subLabel, bullets }) => (
                                <div key={step} className="flex items-start gap-4 py-4 first:pt-0 last:pb-0">
                                    <span className="w-9 h-9 shrink-0 rounded-full bg-gray-900 text-white font-semibold flexCenter mt-0.5">
                                        {step}
                                    </span>
                                    <div className="space-y">
                                        <p className="font-bold">{title}</p>
                                        <p className="textSecondaryColor font-medium">{desc}</p>
                                        {subLabel && (
                                            <p className="font-semibold py-1">{subLabel}</p>
                                        )}
                                        {bullets && (
                                            <ul className="space-y-1">
                                                {bullets.map((item, i) => (
                                                    <li key={i} className="flex items-start gap-1.5 textSecondaryColor font-medium">
                                                        <span className="mt-2 w-1 h-1 rounded-full bg-gray-500 shrink-0" />
                                                        {item}
                                                    </li>
                                                ))}
                                            </ul>
                                        )}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Referral code input */}
                    <div className="space-y-2">
                        <p className="">{t('yourReferralCode')}</p>
                        <div className="flex items-center border border-gray-200 rounded-xl overflow-hidden">
                            <span className="px-4 py-3 textSecondaryColor">
                                <PiGift size={20} />
                            </span>
                            <span className="flex-1 py-3 font-medium select-all">
                                {referralCode || '—'}
                            </span>
                            <button
                                onClick={handleCopy}
                                disabled={!referralCode}
                                className="flex items-center gap-1.5 px-4 py-3 font-medium primaryColor border-l border-gray-200 hover:bg-gray-50 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                            >
                                {copied ? <PiCheck size={16} /> : <PiCopy size={16} />}
                                <span className="hidden md:inline">{copied ? t('copied') : t('copyCode')}</span>
                            </button>
                        </div>
                    </div>

                </div>
            </ProfileLayout>
        </Layout>
    )
}

export default ReferralEarn
